services:
    connection_repository:
        class: AppBundle\Entity\ConnectionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:Connection

    connection_request_repository:
        class: AppBundle\Entity\ConnectionRequestRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:ConnectionRequest

    user_repository:
        class: AppBundle\Entity\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:User

    category_repository:
        class: AppBundle\Entity\CategoryRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:Category

    city_repository:
        class: AppBundle\Entity\CityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:City

    pre_match_repository:
        class: AppBundle\Entity\PreMatchRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:PreMatch

    municipality_repository:
        class: AppBundle\Entity\MunicipalityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:Municipality

    instagram_image_repository:
        class: AppBundle\Entity\InstagramImageRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - AppBundle:InstagramImage
