security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER
        ROLE_COMPLETE_USER: ROLE_USER
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
 
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_token_generator: form.csrf_provider
                login_path: /login
                check_path: /login_check
                success_handler: success_handler
            logout:       true
            anonymous:    true
 
        login:
            pattern:  ^/login$
            security: false
 
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/user, role: ROLE_USER }
