services:
    email_sender:
        class: AppBundle\Service\EmailSender
        arguments:
            - @mailer
            - @templating

    event_listener.send_connection_created_email:
        class: AppBundle\EventListener\SendConnectionCreatedEmailListener
        arguments:
            - @email_sender
        tags:
            - { name: kernel.event_listener, event: connection.created, method: whenConnectionCreated }

    registration.form.type:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    success_handler:
        class: AppBundle\Security\SuccessHandler
        arguments:
            - @router

    twig.app_extension:
        class: AppBundle\Twig\AppExtension
        tags:
            - { name: twig.extension }

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
