<?php

namespace AppBundle\Enum;

class Countries
{
    /**
     * @var string[]
     */
    protected static $countries = [
        'AD' => ['Andorra', 'Andorra'],
        'AE' => ['Förenade Arabemiraten', 'United Arab Emirates'],
        'AF' => ['Afghanistan', 'Afghanistan'],
        'AG' => ['Antigua och Barbuda', 'Antigua and Barbuda'],
        'AI' => ['Anguilla', 'Anguilla'],
        'AL' => ['Albanien', 'Albania'],
        'AM' => ['Armenien', 'Armenia'],
        'AN' => ['Nederländska Antillerna', 'Netherlands Antilles'],
        'AO' => ['Angola', 'Angola'],
        'AQ' => ['Antarktis', 'Antarctica'],
        'AR' => ['Argentina', 'Argentina'],
        'AS' => ['Amerikanska Samoa', 'American Samoa'],
        'AT' => ['Österrike', 'Austria'],
        'AU' => ['Australien', 'Australia'],
        'AW' => ['Aruba', 'Aruba'],
        'AX' => ['Åland', 'Aland Islands'],
        'AZ' => ['Azerbajdzjan', 'Azerbaijan'],
        'BA' => ['Bosnien och Hercegovina', 'Bosnia and Herzegovina'],
        'BB' => ['Barbados', 'Barbados'],
        'BD' => ['Bangladesh', 'Bangladesh'],
        'BE' => ['Belgien', 'Belgium'],
        'BF' => ['Burkina Faso', 'Burkina Faso'],
        'BG' => ['Bulgarien', 'Bulgaria'],
        'BH' => ['Bahrain', 'Bahrain'],
        'BI' => ['Burundi', 'Burundi'],
        'BJ' => ['Benin', 'Benin'],
        'BL' => ['Saint-Barthélemy', 'Saint-Barthélemy'],
        'BM' => ['Bermuda', 'Bermuda'],
        'BN' => ['Brunei', 'Brunei Darussalam'],
        'BO' => ['Bolivia', 'Bolivia'],
        'BR' => ['Brasilien', 'Brazil'],
        'BS' => ['Bahamas', 'Bahamas'],
        'BT' => ['Bhutan', 'Bhutan'],
        'BV' => ['Bouvetön', 'Bouvet Island'],
        'BW' => ['Botswana', 'Botswana'],
        'BY' => ['Vitryssland', 'Belarus'],
        'BZ' => ['Belize', 'Belize'],
        'CA' => ['Kanada', 'Canada'],
        'CC' => ['Kokosöarna', 'Cocos (Keeling) Islands'],
        'CD' => ['Demokratiska republiken Kongo', 'Congo, (Kinshasa)'],
        'CF' => ['Centralafrikanska republiken', 'Central African Republic'],
        'CG' => ['Kongo-Brazzaville', 'Congo (Brazzaville)'],
        'CH' => ['Schweiz', 'Switzerland'],
        'CI' => ['Elfenbenskusten', 'Côte d\'Ivoire'],
        'CK' => ['Cooköarna', 'Cook Islands'],
        'CL' => ['Chile', 'Chile'],
        'CM' => ['Kamerun', 'Cameroon'],
        'CN' => ['Kina', 'China'],
        'CO' => ['Colombia', 'Colombia'],
        'CR' => ['Costa Rica', 'Costa Rica'],
        'CU' => ['Kuba', 'Cuba'],
        'CV' => ['Kap Verde', 'Cape Verde'],
        'CX' => ['Julön', 'Christmas Island'],
        'CY' => ['Cypern', 'Cyprus'],
        'CZ' => ['Tjeckien', 'Czech Republic'],
        'DE' => ['Tyskland', 'Germany'],
        'DJ' => ['Djibouti', 'Djibouti'],
        'DK' => ['Danmark', 'Denmark'],
        'DM' => ['Dominica', 'Dominica'],
        'DO' => ['Dominikanska republiken', 'Dominican Republic'],
        'DZ' => ['Algeriet', 'Algeria'],
        'EC' => ['Ecuador', 'Ecuador'],
        'EE' => ['Estland', 'Estonia'],
        'EG' => ['Egypten', 'Egypt'],
        'EH' => ['Västsahara', 'Western Sahara'],
        'ER' => ['Eritrea', 'Eritrea'],
        'ES' => ['Spanien', 'Spain'],
        'ET' => ['Etiopien', 'Ethiopia'],
        'FI' => ['Finland', 'Finland'],
        'FJ' => ['Fiji', 'Fiji'],
        'FK' => ['Falklandsöarna', 'Falkland Islands (Malvinas)'],
        'FM' => ['Mikronesiska federationen', 'Micronesia, Federated States of'],
        'FO' => ['Färöarna', 'Faroe Islands'],
        'FR' => ['Frankrike', 'France'],
        'FX' => ['France métropolitaine (Frankrike, europeiska delen)', 'France métropolitaine'],
        'GA' => ['Gabon', 'Gabon'],
        'GB' => ['Storbritannien', 'United Kingdom'],
        'GD' => ['Grenada', 'Grenada'],
        'GE' => ['Georgien', 'Georgia'],
        'GF' => ['Franska Guyana', 'French Guiana'],
        'GG' => ['Guernsey', 'Guernsey'],
        'GH' => ['Ghana', 'Ghana'],
        'GI' => ['Gibraltar', 'Gibraltar'],
        'GL' => ['Grönland', 'Greenland'],
        'GM' => ['Gambia', 'Gambia'],
        'GN' => ['Guinea', 'Guinea'],
        'GP' => ['Guadeloupe', 'Guadeloupe'],
        'GQ' => ['Ekvatorialguinea', 'Equatorial Guinea'],
        'GR' => ['Grekland', 'Greece'],
        'GT' => ['Guatemala', 'Guatemala'],
        'GU' => ['Guam', 'Guam'],
        'GW' => ['Guinea Bissau', 'Guinea-Bissau'],
        'GY' => ['Guyana', 'Guyana'],
        'HK' => ['Hongkong', 'Hong Kong, SAR China'],
        'HM' => ['Heard- och McDonaldsöarna', 'Heard and Mcdonald Islands'],
        'HN' => ['Honduras', 'Honduras'],
        'HR' => ['Kroatien', 'Croatia'],
        'HT' => ['Haiti', 'Haiti'],
        'HU' => ['Ungern', 'Hungary'],
        'ID' => ['Indonesien', 'Indonesia'],
        'IE' => ['Irland', 'Ireland'],
        'IL' => ['Israel', 'Israel'],
        'IM' => ['Isle of Man', 'Isle of Man'],
        'IN' => ['Indien', 'India'],
        'IO' => ['Brittiska territoriet i Indiska Oceanen', 'British Indian Ocean Territory'],
        'IQ' => ['Irak', 'Iraq'],
        'IR' => ['Iran', 'Iran, Islamic Republic of'],
        'IS' => ['Island', 'Iceland'],
        'IT' => ['Italien', 'Italy'],
        'JE' => ['Jersey', 'Jersey'],
        'JM' => ['Jamaica', 'Jamaica'],
        'JO' => ['Jordanien', 'Jordan'],
        'JP' => ['Japan', 'Japan'],
        'KE' => ['Kenya', 'Kenya'],
        'KG' => ['Kirgizistan', 'Kyrgyzstan'],
        'KH' => ['Kambodja', 'Cambodia'],
        'KI' => ['Kiribati', 'Kiribati'],
        'KM' => ['Komorerna', 'Comoros'],
        'KN' => ['Saint Kitts och Nevis', 'Saint Kitts and Nevis'],
        'KP' => ['Nordkorea', 'Korea (North)'],
        'KR' => ['Sydkorea', 'Korea (South)'],
        'KW' => ['Kuwait', 'Kuwait'],
        'KY' => ['Caymanöarna', 'Cayman Islands'],
        'KZ' => ['Kazakstan', 'Kazakhstan'],
        'LA' => ['Laos', 'Lao PDR'],
        'LB' => ['Libanon', 'Lebanon'],
        'LC' => ['Saint Lucia', 'Saint Lucia'],
        'LI' => ['Liechtenstein', 'Liechtenstein'],
        'LK' => ['Sri Lanka', 'Sri Lanka'],
        'LR' => ['Liberia', 'Liberia'],
        'LS' => ['Lesotho', 'Lesotho'],
        'LT' => ['Litauen', 'Lithuania'],
        'LU' => ['Luxemburg', 'Luxembourg'],
        'LV' => ['Lettland', 'Latvia'],
        'LY' => ['Libyen', 'Libya'],
        'MA' => ['Marocko', 'Morocco'],
        'MC' => ['Monaco', 'Monaco'],
        'MD' => ['Moldavien', 'Moldova'],
        'ME' => ['Montenegro', 'Montenegro'],
        'MG' => ['Madagaskar', 'Madagascar'],
        'MH' => ['Marshallöarna', 'Marshall Islands'],
        'MK' => ['Makedonien', 'Macedonia, Republic of'],
        'ML' => ['Mali', 'Mali'],
        'MM' => ['Burma', 'Myanmar'],
        'MN' => ['Mongoliet', 'Mongolia'],
        'MO' => ['Macau', 'Macao, SAR China'],
        'MP' => ['Nordmarianerna', 'Northern Mariana Islands'],
        'MQ' => ['Martinique', 'Martinique'],
        'MR' => ['Mauretanien', 'Mauritania'],
        'MS' => ['Montserrat', 'Montserrat'],
        'MT' => ['Malta', 'Malta'],
        'MU' => ['Mauritius', 'Mauritius'],
        'MV' => ['Maldiverna', 'Maldives'],
        'MW' => ['Malawi', 'Malawi'],
        'MX' => ['Mexiko', 'Mexico'],
        'MY' => ['Malaysia', 'Malaysia'],
        'MZ' => ['Moçambique', 'Mozambique'],
        'NA' => ['Namibia', 'Namibia'],
        'NC' => ['Nya Kaledonien', 'New Caledonia'],
        'NE' => ['Niger', 'Niger'],
        'NF' => ['Norfolkön', 'Norfolk Island'],
        'NG' => ['Nigeria', 'Nigeria'],
        'NI' => ['Nicaragua', 'Nicaragua'],
        'NL' => ['Nederländerna', 'Netherlands'],
        'NO' => ['Norge', 'Norway'],
        'NP' => ['Nepal', 'Nepal'],
        'NR' => ['Nauru', 'Nauru'],
        'NU' => ['Niue', 'Niue'],
        'NZ' => ['Nya Zeeland', 'New Zealand'],
        'OM' => ['Oman', 'Oman'],
        'PA' => ['Panama', 'Panama'],
        'PE' => ['Peru', 'Peru'],
        'PF' => ['Franska Polynesien', 'French Polynesia'],
        'PG' => ['Papua Nya Guinea', 'Papua New Guinea'],
        'PH' => ['Filippinerna', 'Philippines'],
        'PK' => ['Pakistan', 'Pakistan'],
        'PL' => ['Polen', 'Poland'],
        'PM' => ['Saint-Pierre och Miquelon', 'Saint Pierre and Miquelon'],
        'PN' => ['Pitcairnöarna', 'Pitcairn'],
        'PR' => ['Puerto Rico', 'Puerto Rico'],
        'PS' => ['Palestina', 'Palestinian Territory'],
        'PT' => ['Portugal', 'Portugal'],
        'PW' => ['Palau', 'Palau'],
        'PY' => ['Paraguay', 'Paraguay'],
        'QA' => ['Qatar', 'Qatar'],
        'RE' => ['Réunion', 'Réunion'],
        'RO' => ['Rumänien', 'Romania'],
        'RS' => ['Serbien', 'Serbia'],
        'RU' => ['Ryssland', 'Russian Federation'],
        'RW' => ['Rwanda', 'Rwanda'],
        'SA' => ['Saudiarabien', 'Saudi Arabia'],
        'SB' => ['Salomonöarna', 'Solomon Islands'],
        'SC' => ['Seychellerna', 'Seychelles'],
        'SD' => ['Sudan', 'Sudan'],
        'SE' => ['Sverige', 'Sweden'],
        'SG' => ['Singapore', 'Singapore'],
        'SH' => ['Sankta Helena', 'Saint Helena'],
        'SI' => ['Slovenien', 'Slovenia'],
        'SJ' => ['Svalbard och Jan Mayen', 'Svalbard and Jan Mayen Islands'],
        'SK' => ['Slovakien', 'Slovakia'],
        'SL' => ['Sierra Leone', 'Sierra Leone'],
        'SM' => ['San Marino', 'San Marino'],
        'SN' => ['Senegal', 'Senegal'],
        'SO' => ['Somalia', 'Somalia'],
        'SR' => ['Surinam', 'Suriname'],
        'ST' => ['São Tomé och Príncipe', 'Sao Tome and Principe'],
        'SV' => ['El Salvador', 'El Salvador'],
        'SY' => ['Syrien', 'Syrian Arab Republic (Syria)'],
        'SZ' => ['Swaziland', 'Swaziland'],
        'TC' => ['Turks- och Caicosöarna', 'Turks and Caicos Islands'],
        'TD' => ['Tchad', 'Chad'],
        'TF' => ['Franska södra territorierna', 'French Southern Territories'],
        'TG' => ['Togo', 'Togo'],
        'TH' => ['Thailand', 'Thailand'],
        'TJ' => ['Tadzjikistan', 'Tajikistan'],
        'TK' => ['Tokelauöarna', 'Tokelau'],
        'TM' => ['Turkmenistan', 'Timor-Leste'],
        'TN' => ['Tunisien', 'Turkmenistan'],
        'TO' => ['Tonga', 'Tunisia'],
        'TP' => ['Östtimor', 'Tonga'],
        'TR' => ['Turkiet', 'Turkey'],
        'TT' => ['Trinidad och Tobago', 'Trinidad and Tobago'],
        'TV' => ['Tuvalu', 'Tuvalu'],
        'TW' => ['Taiwan', 'Taiwan, Republic of China'],
        'TZ' => ['Tanzania', 'Tanzania, United Republic of'],
        'UA' => ['Ukraina', 'Ukraine'],
        'UG' => ['Uganda', 'Uganda'],
        'UM' => ['USA:s yttre öar', 'US Minor Outlying Islands'],
        'US' => ['USA', 'United States of America'],
        'UY' => ['Uruguay', 'Uruguay'],
        'UZ' => ['Uzbekistan', 'Uzbekistan'],
        'VA' => ['Vatikanstaten', 'Holy See (Vatican City State)'],
        'VC' => ['Saint Vincent och Grenadinerna', 'Saint Vincent and Grenadines'],
        'VE' => ['Venezuela', 'Venezuela (Bolivarian Republic)'],
        'VG' => ['Brittiska Jungfruöarna', 'British Virgin Islands'],
        'VI' => ['Amerikanska Jungfruöarna', 'Virgin Islands, US'],
        'VN' => ['Vietnam', 'Viet Nam'],
        'VU' => ['Vanuatu', 'Vanuatu'],
        'WF' => ['Wallis- och Futunaöarna', 'Wallis and Futuna Islands'],
        'WS' => ['Samoa', 'Samoa'],
        'YE' => ['Jemen', 'Yemen'],
        'YT' => ['Mayotte', 'Mayotte'],
        'ZA' => ['Sydafrika', 'South Africa'],
        'ZM' => ['Zambia', 'Zambia'],
        'ZW' => ['Zimbabwe', 'Zimbabwe']
    ];

    /**
     * @param $locale
     *
     * @return string[]
     */
    public static function getList($locale = 'sv')
    {
        // if other language than swedish, show english version
        $locale_index = $locale === 'sv' ? 0 : 1;

        $locale_list = [];
        foreach (static::$countries as $key => $value) {
            $locale_list[$key] = $value[$locale_index];
        }
        asort($locale_list);
        
        return $locale_list;
    }

    /**
     * @param $code
     * @param $locale
     *
     * @return string
     */
    public static function getName($code, $locale = 'sv')
    {
        // if other language than swedish, show english version
        $locale_index = $locale === 'sv' ? 0 : 1;

        if (!isset(static::$countries[$code])) {
            throw new \LogicException(sprintf('Country for code %s was not found.', $code));
        }

        return static::$countries[$code][$locale_index];
    }
}
